
name: Python application

on:
  push:
    branches: [ backend_host ]
  pull_request:
    branches: [ backend_host ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         pytest
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ b63dff64-a7f3-44d9-b6f9-8bdbbc30a70b }}
       # HEROKU_APP_NAME: ${{ cybersolarex }}
      if: github.ref == 'refs/heads/backend_host' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/solarex-final.git
        git push heroku HEAD:master -f
